// docs/api/openapi-1.7.0.json(백엔드 확정 계약, docs/decisions/api-contract-mismatch.md)
// 기준 생성 타입 재노출. 추측으로 작성했던 TEMP 수기 타입(analysis-status,
// error-codes, cause-codes, envelope, 결과 타입)은 전부 지우고 생성 타입으로
// 교체했다 — 계속 손으로 관리하는 파일은 result-usable.ts뿐이다.
export type {
  ActionBurden,
  AlternativeActionDetail,
  AlternativeActionType,
  AlternativeComparisonResponse,
  AlternativeDetail,
  AlternativeKind,
  AlternativeOutcome,
  AlternativePreferencesInput,
  AlternativePreferencesUpdate,
  AlternativeSummary,
  AnalysisCreateRequest,
  AnalysisResponse,
  AnalysisResult,
  AnalysisStatus,
  AnalysisUpdateRequest,
  CashflowPoint,
  CauseCode,
  ClassificationConfirmation,
  ClassificationConfirmationRequest,
  ClassificationReviewItem,
  ConfidenceLevel,
  ContractVersions,
  DataMode,
  DataSource,
  DatasetClassificationSummary,
  DatasetCreateResponse,
  DatasetIntelligence,
  DatasetIntelligenceResponse,
  DatasetStatus,
  DemoScenarioListResponse,
  DemoScenarioSummary,
  EmploymentPlanInput,
  EmploymentPlanUpdate,
  ErrorCode,
  ErrorDetail,
  ErrorEnvelope,
  EvidenceExplanation,
  EvidenceInputFact,
  EvidenceOutputFact,
  EvidenceResponse,
  EvidenceResultType,
  EvidenceRuleFact,
  EvidenceTrace,
  ExplanationFallbackReason,
  ExplanationSource,
  FieldError,
  FinancialInput,
  FinancialUpdate,
  HouseholdInput,
  HouseholdType,
  HouseholdUpdate,
  HTTPValidationError,
  LimitationCode,
  RecurringPattern,
  RiskItem,
  RiskSeverity,
  SafeContributionResult,
  ScenarioCoverage,
  ScenarioRoute,
  StressInput,
  StressUpdate,
  TransactionCategory,
  ValidationError,
} from './generated';

export { isResultUsable } from './result-usable';
